import json
from pathlib import Path
from html import escape as h
R=Path(__file__).resolve().parents[2];H=Path(__file__).resolve().parent
F=json.loads((H/'facts.json').read_text());d=json.loads((R/'dist/schools.json').read_text());ss={s['id']:s for s in d['schools']}
conf=[id for id,v in F.items() if v['applicationFee']['amount'] is not None];free=[id for id in conf if F[id]['applicationFee']['amount']==0]
names=lambda ids:'、'.join(ss[id]['short']+' '+ss[id]['abbr'] for id in ids)
parts=['''<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>23校國立大學／科大核對｜臺灣選校</title><style>*{box-sizing:border-box}body{margin:0;background:#f4f7f4;color:#173127;font:17px/1.8 system-ui,sans-serif}main{max-width:1000px;margin:auto;padding:28px 18px}h1{font-size:28px}h2{font-size:22px}h3{font-size:18px}a{color:#156649;overflow-wrap:anywhere}section,details{background:white;padding:20px;border:1px solid #d3e1d7;border-radius:12px;margin:16px 0}summary{cursor:pointer;font-size:19px;font-weight:700}article{border-top:1px solid #d3e1d7;margin-top:18px;padding-top:12px}.muted{color:#526258}.links{display:flex;flex-wrap:wrap;gap:16px}li{margin:8px 0}p{overflow-wrap:anywhere}</style><main><a href="./?lang=zh&audited=1">← 已核對學校快速篩選</a><h1>新增23所國立大學／科大官方資料核對</h1><p>查核日期：2026-09-28。快速篩選合計51校（原有28校＋本批23校），網站仍保留139校原名單。</p><p lang="my">စစ်ဆေးပြီး ကျောင်း စုစုပေါင်း 51 ကျောင်း။ အချက်အလက်အားလုံး ပြည့်စုံသည်ဟု မဆိုလိုပါ။ အတည်မပြုနိုင်သေးသော အချက်များကို ကျောင်းတစ်ကျောင်းစီတွင် ဖော်ပြထားသည်။</p><p>「已核對」表示完成一輪官方資料核對；本批各校仍列為部分完整，並非所有欄位與所有系所皆已確認。</p>''']
parts.append(f'<section><h2>本批範圍</h2><p>{h(names(F))}</p><p>申請費明確：{len(conf)}校；其中官方明確免收{len(free)}校（{h(names(free))}）。仍缺一般學位生全校費用：{h(names(id for id in F if id not in conf))}。北護另有特定碩士專班費用，未套用全校。</p><p>本批有官方榜單／結果公告入口：{sum(bool(v["admissionNotices"]) for v in F.values())}校。榜單只保留連結，不下載分析、不計算錄取人數／錄取率。個別無公開榜單者保留缺口。</p><p>範圍為原139校中的剩餘國立大學及國立科大；不另新增學校，也不把國立專科、學院或市立大學混入本批。</p></section>')
parts.append('''<section><h2>重要更新與修正</h2><ul><li>北教大、高雄大學、金門大學已找到116秋季正式資料；其餘可核得的115秋季保留原始年度，顯示歷年月份參考。</li><li>屏東大學最新2026–2027簡章明載免申請費；嘉義、高雄、屏科、北商也有官方免收依據。缺收費文字的學校不填0元。</li><li>中教大、國體、臺體申請費按學制顯示；北護US$100僅蒙特梭利碩士專班。北藝免收也只限符合指定SAC／ICDF条件者。</li><li>國體115秋季截止中文6/18、英文6/20保留衝突；嘉大、東華、宜蘭原有日期差異持續保留，不自行選日。</li><li>嘉大第二梯只適用學士；臺藝115簡章明載不招春季。北護新系統2027日期屬僑港澳，不套到外國學位生。</li><li>金門新生生活津貼的英文招生頁與中文及正式辦法有差異，依正式辦法標示擇優與名額。高科碩博採115/2/25新版，不沿用舊快取中的學士津貼。</li><li>屏科僅官網常態每年申請期，未冒充116正式日程。北藝、南藝、澎科及北商保留郵寄／親送／電郵等實際申請方式提醒。</li></ul></section><section><h2>仍有缺口</h2><p>部分學校未公開開始日、費用或歷年公開榜單。獎學金依新生／在校生、學制與版本區分；金額未明或需要審查者不視為保證取得。學雜費、住宿與各系文件語言條件尚未完成同年度全面整理，不提供看似精準的第一年總成本。</p><p>緬文保留主要操作、狀態及說明；新加入的細節以中文與官方原文為準，未宣稱完成專業緬文逐條校譯。</p></section><div class="links"><a href="school-insights.json" download>費用、獎學金與榜單 JSON</a><a href="admission-records.json" download>招生日期 JSON</a><a href="national-audit.html">前批17校核對報告</a></div>''')
for id,v in F.items():
 s=ss[id];f=v['applicationFee'];amt=f.get('amountLabel') or ('未核得一般學位生全校明確費用' if f['amount'] is None else 'NT$'+format(f['amount'],','))
 parts.append(f'<details id="{id}"><summary>{h(s["name"])} {h(s["abbr"])} · 部分完整</summary><h3>申請費：{h(amt)}</h3><p>{h(f["academicYear"])} · {h(f["notes"])}</p><a href="{h(f["sourceUrl"],quote=True)}" target="_blank" rel="noopener">官方費用依據／已檢查資料 ↗</a>')
 for sch in v['scholarships']:parts.append('<article><h3>'+h(sch['scope'])+'</h3><p>'+h(sch['award'])+'</p><p>'+h(sch['continuation'])+'</p><p class="muted">'+h(sch['academicYear'])+'</p><a target="_blank" rel="noopener" href="'+h(sch['sourceUrl'],quote=True)+'">官方制度 ↗</a></article>')
 parts.append('<h3>官方原始榜單／結果公告</h3><ul>')
 for n in v['admissionNotices']:parts.append('<li><a target="_blank" rel="noopener" href="'+h(n['sourceUrl'],quote=True)+'">'+h(n['sourceTitle'])+'</a></li>')
 if not v['admissionNotices']:parts.append('<li>尚未找到官方公開原始榜單。</li>')
 parts.append('</ul><h3>尚待確認</h3><ul>'+''.join('<li>'+h(x)+'</li>' for x in v['audit']['gaps'])+'</ul></details>')
parts.append('</main></html>');(R/'dist/remaining-national-audit.html').write_text(''.join(parts))
print('Report:23; confirmed fees',len(conf),'explicit free',len(free),'notices',sum(bool(v['admissionNotices']) for v in F.values()))
