import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseHTML} from 'linkedom';
const data=JSON.parse(fs.readFileSync(new URL('../../dist/schools.json',import.meta.url)));
const insights=JSON.parse(fs.readFileSync(new URL('../../dist/school-insights.json',import.meta.url)));
const {window,document}=parseHTML(fs.readFileSync(new URL('../../dist/index.html',import.meta.url),'utf8'));
globalThis.window=window;globalThis.document=document;
globalThis.location=new URL('https://example.test/?lang=zh&term=fall&audited=1');globalThis.history={replaceState:(a,b,url)=>{globalThis.location=new URL(url,location)}};
const saved=new Map();globalThis.localStorage={getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)};
globalThis.fetch=async url=>({ok:true,json:async()=>String(url).includes('school-insights')?insights:data});
window.HTMLElement.prototype.scrollIntoView=function(){};
const dialog=document.querySelector('dialog');dialog.showModal=function(){this.open=true;};dialog.close=function(){this.open=false;};
const tools=new Map();document.modelContext={registerTool:t=>tools.set(t.name,t)};
await import('../../dist/app.js');
const click=selector=>{const el=document.querySelector(selector);assert.ok(el,selector);el.dispatchEvent(new window.Event('click',{bubbles:true}));};
const count=()=>Number(document.querySelector('.result-count').textContent);
const pressed=()=>document.querySelector('[data-action="audited"]').getAttribute('aria-pressed');
assert.equal(count(),28);assert.equal(pressed(),'true');
assert.equal(document.querySelectorAll('article.school').length,12);
click('[data-action="audited"]');assert.equal(count(),139);assert.equal(pressed(),'false');assert.equal(new URLSearchParams(location.search).has('audited'),false);
click('[data-action="audited"]');assert.equal(count(),28);assert.equal(new URLSearchParams(location.search).get('audited'),'1');
const filter=tools.get('filter_taiwan_schools');
filter.execute({city:'臺中市'});assert.equal(count(),11);
click('[data-term="spring"]');assert.equal(count(),11);assert.equal(pressed(),'true');
click('[data-lang="my"]');assert.equal(document.documentElement.lang,'my');assert.match(document.querySelector('[data-action="audited"]').textContent,/စစ်ဆေး/);
click('[data-lang="zh"]');filter.execute({city:'',q:'NCNU'});assert.equal(count(),1);
click('[data-detail]');assert.ok(dialog.open);assert.match(document.querySelector('.school-insights').textContent,/秋季規定直接推定/);assert.match(document.querySelector('.school-insights').textContent,/114春季一般外國學生/);click('[data-action="close"]');
filter.execute({q:'NUU',term:'fall'});click('[data-detail]');assert.match(document.querySelector('.fee-result').textContent,/未找到/);assert.match(document.querySelector('.school-insights').textContent,/6,000/);click('[data-action="close"]');
click('[data-save]');click('[data-action="favorites"]');assert.equal(count(),1);assert.equal(pressed(),'true');
filter.execute({q:'',favorites:false,city:'臺北市'});assert.ok(count()>0&&count()<28);
click('[data-remove-filter="audited"]');assert.equal(pressed(),'false');assert.equal(document.querySelector('[data-filter="city"]').value,'臺北市');
click('[data-action="reset"]');assert.equal(count(),139);assert.equal(pressed(),'false');
filter.execute({audited:true,q:'NTUST',term:'spring'});click('[data-detail]');assert.match(document.querySelector('.school-insights').textContent,/中文學程不提供/);click('[data-action="close"]');
click('[data-action="sources"]');assert.ok(document.querySelector('a[href$="national-audit.html"]'));click('[data-action="close"]');
filter.execute({q:'',city:'苗栗縣'});assert.equal(count(),1);
filter.execute({q:'zzzzzz'});assert.equal(count(),0);assert.ok(document.querySelector('.empty'));assert.equal(pressed(),'true');
click('[data-action="reset"]');assert.equal(count(),139);
console.log('PASS: shared audited URL opens28; reversible filter; Taichung11; city/semester/Chinese/Myanmar combinations; bookmarks; unknown fees; scope warnings; report link; empty-state recovery. DOM simulation, not a rendered browser test.');
