import fs from 'node:fs';import assert from 'node:assert/strict';
import {parseHTML} from 'linkedom';
import {monthlyEvents} from '../../dist/weiquan.js';
const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url)));
const data=read('../../dist/schools.json'),ins=read('../../dist/school-insights.json'),old=read('./schools-before.json'),oi=read('./insights-before.json');
const ids=data.schools.filter(s=>s.weiquan).map(s=>s.id);assert.equal(ids.length,27);assert.equal(data.schools.length,139);
for(const s of data.schools)if(!ids.includes(s.id)){assert.deepEqual(s,old.schools.find(x=>x.id===s.id));assert.deepEqual(ins.schools[s.id],oi.schools[s.id]);}
const events=monthlyEvents(data.schools);assert.ok(events.rows.length>100);
assert.ok(events.rows.every(r=>ids.includes(r.id)&&r.e.status!=='conflict'));
assert.ok(events.rows.some(r=>r.id==='0047'&&r.key==='start'&&r.date==='2026-11-02'&&r.e.status==='official'));
assert.ok(events.rows.some(r=>r.id==='0047'&&r.key==='end'&&r.date==='2026-12-17'));
assert.ok(events.rows.some(r=>r.id==='0047'&&r.key==='result'&&r.e.status==='historical'));
assert.ok(events.rows.filter(r=>r.id==='0025'&&r.term==='spring').every(r=>r.scope==='graduate'));
assert.equal(ins.schools['0031'].applicationFee.amount,null);assert.equal(ins.schools['0025'].applicationFee.amount,0);
assert.deepEqual(ins.schools['0025'].applicationFee.intakes,['spring']);assert.match(ins.schools['0051'].scholarships[0].award,/每學期/);
const {window,document}=parseHTML(fs.readFileSync(new URL('../../dist/index.html',import.meta.url),'utf8'));
globalThis.window=window;globalThis.document=document;globalThis.location=new URL('https://example.test/?lang=zh&weiquan=1');globalThis.history={replaceState:(a,b,u)=>{globalThis.location=new URL(u,location)}};
const saved=new Map();globalThis.localStorage={getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)};
globalThis.fetch=async u=>({ok:true,json:async()=>String(u).includes('school-insights')?ins:data});window.HTMLElement.prototype.scrollIntoView=function(){};
const dialog=document.querySelector('dialog');dialog.showModal=function(){this.open=true};dialog.close=function(){this.open=false;this.dispatchEvent(new window.Event('close'))};
await import('../../dist/app.js');
const click=q=>{const n=document.querySelector(q);assert.ok(n,q);n.dispatchEvent(new window.Event('click',{bubbles:true}))};
const change=(q,v)=>{const n=document.querySelector(q);assert.ok(n);Object.defineProperty(n,'value',{value:v,configurable:true});n.dispatchEvent(new window.Event('change',{bubbles:true}))};
const count=()=>Number(document.querySelector('.result-count').textContent);
assert.equal(count(),27);click('[data-action="weiquan"]');assert.ok(dialog.open);assert.equal(document.querySelectorAll('.wq-column').length,3);
change('[data-wq-month]','2026-11');assert.match(dialog.textContent,/高餐/);assert.match(document.querySelector('.wq-start').textContent,/11\/02/);
change('[data-wq-term]','fall');assert.equal(document.querySelectorAll('.wq-season.spring').length,0);
click('.wq-start [data-detail="0047"]');assert.match(document.querySelector('.detail-semester').textContent,/秋/);assert.match(dialog.textContent,/2026/);assert.ok(document.querySelector('[data-action="wq-back"]'));
click('[data-action="wq-back"]');assert.equal(document.querySelector('[data-wq-month]').value,'2026-11');
click('[data-wq-step="1"]');assert.match(document.querySelector('.wq-end').textContent,/12\/17/);
click('[data-action="close"]');assert.equal(dialog.open,false);click('[data-lang="my"]');click('[data-action="weiquan"]');assert.match(dialog.textContent,/လျှောက်/);click('[data-action="close"]');
click('[data-remove-filter="weiquan"]');assert.equal(count(),139);assert.ok(!location.search.includes('weiquan=1'));
click('[data-action="weiquan"]');click('[data-action="close"]');click('[data-action="reset"]');assert.equal(count(),139);
console.log('PASS: only27 selected schools modified; 139 registry; personal share/filter/reset; 3 event columns; November/December NKUHT official dates; historical results; graduate scope; no conflict-as-date; bilingual controls; correct-semester details and return-to-month. DOM test.');
